
question_data_1 = [{"category": "Entertainment: Video Games",
  "type": "boolean", "difficulty": "easy",
  "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
  "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
  "difficulty": "easy",
  "question": "The anime 'Lucky Star' follows the story of one girl who is unaware she is God.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
  "question": "You can legally drink alcohol while driving in Mississippi.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game's plot.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
  "question": "HTML stands for Hypertext Markup Language.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
  "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Sports", "type": "boolean", "difficulty": "easy",
  "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
  "question": "Actor Tommy Chong served prison time.", "correct_answer": "True",
  "incorrect_answers": ["False"]},
 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
  "difficulty": "easy", "question": "In Chobits, Hideki found Chii in his apartment.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Geography", "type": "boolean", "difficulty": "easy",
  "question": "Nova Scotia is on the east coast of Canada.", "correct_answer": "True",
  "incorrect_answers": ["False"]}]

question_data_2 = [{"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
 "question": "A universal set, or a set that contains all sets, exists.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"category": "History", "type": "boolean", "difficulty": "easy",
 "question": "The United States was a member of the League of Nations.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "question": "The Sun rises from the North.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
 "question": "Shaquille O'Neal appeared in the 1997 film 'Space Jam'.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "In the game 'Subnautica', a 'Spadefish' will attack you.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
 "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
 "incorrect_answers": ["True"]},
{"category": "Animals", "type": "boolean", "difficulty": "easy",
 "question": "A caterpillar has more muscles than humans do.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Politics", "type": "boolean", "difficulty": "easy",
 "question": "One of Barack Obama's United States presidential campaign slogan's was 'Yes We Can';.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
 "question": "Daft Punk originated in France.", "correct_answer": "True",
 "incorrect_answers": ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "The game 'Jetpack Joyride' was created by 'Redbrick Studios'.",
 "correct_answer": "False", "incorrect_answers": ["True"]}
]

question_data_3 = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
 "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "'Undertale' is an RPG created by Toby Fox and released in 2015.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Vehicles", "type": "boolean", "difficulty": "easy",
 "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
 "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
 "question": "George Lucas directed the entire original Star Wars trilogy.",
 "correct_answer": "False", "incorrect_answers": ["True"]},
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "question": "'27 Club'; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
 "question": "The ghosts in 'Pac-Man'and'Ms. Pac-Man' have completely different behavior.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
 "question": "The National Animal of Scotland is the Unicorn.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
 "question": "'Foodfight!'earned less than $80,000 at box office.",
 "correct_answer": "True", "incorrect_answers": ["False"]},
{"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
 "question": "'The Simpsons' family is named after creator Matt Groening's real family.",
 "correct_answer": "True", "incorrect_answers": ["False"]}
]

question_banks = [question_data_1, question_data_2, question_data_3]